#!/usr/bin/env python3
"""
TASK-001 PoC: Rich HTML Export

Demonstrates exporting Rich terminal output to HTML.
Run: python rich_html_export.py
Output: sample_output.html
"""

from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

# Sample scan results
SAMPLE_RESULTS = {
    "scan_info": {
        "target": "/home/user/ansible-project",
        "timestamp": "2026-03-13T14:30:00Z",
        "version": "0.1.0",
    },
    "summary": {
        "total": 12,
        "errors": 2,
        "warnings": 7,
        "hints": 3,
    },
    "issues": [
        {"rule": "L001", "severity": "error", "message": "Module 'apt' should use FQCN 'ansible.builtin.apt'", "file": "playbook.yml", "line": 15},
        {"rule": "L001", "severity": "error", "message": "Module 'yum' should use FQCN 'ansible.builtin.yum'", "file": "playbook.yml", "line": 23},
        {"rule": "M002", "severity": "warning", "message": "Parameter 'state=latest' is deprecated in ansible-core 2.16+", "file": "tasks/main.yml", "line": 8},
        {"rule": "M003", "severity": "warning", "message": "Module 'include' deprecated, use 'ansible.builtin.include_tasks'", "file": "playbook.yml", "line": 45},
        {"rule": "R001", "severity": "warning", "message": "Using 'shell' when 'command' would suffice", "file": "handlers/main.yml", "line": 12},
        {"rule": "P001", "severity": "warning", "message": "Missing 'become' declaration at play level", "file": "playbook.yml", "line": 1},
        {"rule": "SEC001", "severity": "warning", "message": "Potential hardcoded password detected", "file": "vars/main.yml", "line": 5},
        {"rule": "M004", "severity": "warning", "message": "Collection 'community.general' not in requirements.yml", "file": "playbook.yml", "line": 30},
        {"rule": "M005", "severity": "warning", "message": "Using deprecated 'with_items' loop syntax", "file": "tasks/main.yml", "line": 20},
        {"rule": "L002", "severity": "hint", "message": "Consider using 'ansible.builtin.debug' instead of 'debug'", "file": "playbook.yml", "line": 50},
        {"rule": "L003", "severity": "hint", "message": "Task name could be more descriptive", "file": "tasks/main.yml", "line": 1},
        {"rule": "L004", "severity": "hint", "message": "Consider adding 'changed_when' for shell task", "file": "handlers/main.yml", "line": 12},
    ],
}


def render_report(console: Console, results: dict) -> None:
    """Render the full scan report."""
    info = results["scan_info"]
    summary = results["summary"]

    # Header
    console.print()
    console.rule("[bold blue]APME Scan Report[/bold blue]")
    console.print()

    # Scan info panel
    info_text = (
        f"[bold]Target:[/bold] {info['target']}\n"
        f"[bold]Scanned:[/bold] {info['timestamp']}\n"
        f"[bold]APME Version:[/bold] {info['version']}"
    )
    console.print(Panel(info_text, title="Scan Information", border_style="blue"))
    console.print()

    # Summary panel with color-coded counts
    if summary["errors"] > 0:
        status_color = "red"
        status_text = "FAILED"
    elif summary["warnings"] > 0:
        status_color = "yellow"
        status_text = "WARNINGS"
    else:
        status_color = "green"
        status_text = "PASSED"

    summary_text = (
        f"[bold {status_color}]Status: {status_text}[/bold {status_color}]\n\n"
        f"[red]● Errors:[/red] {summary['errors']}\n"
        f"[yellow]● Warnings:[/yellow] {summary['warnings']}\n"
        f"[blue]● Hints:[/blue] {summary['hints']}\n"
        f"[dim]─────────────[/dim]\n"
        f"[bold]Total:[/bold] {summary['total']}"
    )
    console.print(Panel(summary_text, title="Summary", border_style=status_color))
    console.print()

    # Issues table
    table = Table(
        title="Issues",
        show_header=True,
        header_style="bold white on dark_blue",
        border_style="blue",
        show_lines=True,
    )

    table.add_column("Rule", style="cyan", width=8, justify="center")
    table.add_column("Severity", width=10, justify="center")
    table.add_column("Message", style="white", min_width=40)
    table.add_column("Location", style="dim", width=25)

    severity_styles = {
        "error": "[bold white on red] ERROR [/bold white on red]",
        "warning": "[black on yellow] WARN  [/black on yellow]",
        "hint": "[white on blue] HINT  [/white on blue]",
    }

    for issue in results["issues"]:
        table.add_row(
            issue["rule"],
            severity_styles.get(issue["severity"], issue["severity"]),
            issue["message"],
            f"{issue['file']}:{issue['line']}",
        )

    console.print(table)
    console.print()

    # Footer
    console.rule("[dim]Generated by APME CLI[/dim]")
    console.print()


def main() -> None:
    # Create console with recording enabled
    console = Console(record=True, width=120)

    # Render the report
    render_report(console, SAMPLE_RESULTS)

    # Export to HTML
    output_path = Path(__file__).parent / "sample_output.html"
    console.save_html(str(output_path), theme=None)

    print(f"HTML report saved to: {output_path}")
    print(f"Open in browser: file://{output_path.absolute()}")

    # Also print to terminal for preview
    preview_console = Console()
    render_report(preview_console, SAMPLE_RESULTS)


if __name__ == "__main__":
    main()
