# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from apme.v1 import common_pb2 as apme_dot_v1_dot_common__pb2
from apme.v1 import primary_pb2 as apme_dot_v1_dot_primary__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in apme/v1/primary_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrimaryStub(object):
    """Primary is the orchestrator daemon: receives chunked fs, runs engine + validators, returns violations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Scan = channel.unary_unary(
                '/apme.v1.Primary/Scan',
                request_serializer=apme_dot_v1_dot_primary__pb2.ScanRequest.SerializeToString,
                response_deserializer=apme_dot_v1_dot_primary__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.ScanStream = channel.stream_unary(
                '/apme.v1.Primary/ScanStream',
                request_serializer=apme_dot_v1_dot_primary__pb2.ScanChunk.SerializeToString,
                response_deserializer=apme_dot_v1_dot_primary__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.Format = channel.unary_unary(
                '/apme.v1.Primary/Format',
                request_serializer=apme_dot_v1_dot_primary__pb2.FormatRequest.SerializeToString,
                response_deserializer=apme_dot_v1_dot_primary__pb2.FormatResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/apme.v1.Primary/Health',
                request_serializer=apme_dot_v1_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=apme_dot_v1_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)


class PrimaryServicer(object):
    """Primary is the orchestrator daemon: receives chunked fs, runs engine + validators, returns violations.
    """

    def Scan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanStream(self, request_iterator, context):
        """ScanStream sends file batches in multiple messages to avoid gRPC max message size (default 4 MiB).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Format(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrimaryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Scan': grpc.unary_unary_rpc_method_handler(
                    servicer.Scan,
                    request_deserializer=apme_dot_v1_dot_primary__pb2.ScanRequest.FromString,
                    response_serializer=apme_dot_v1_dot_primary__pb2.ScanResponse.SerializeToString,
            ),
            'ScanStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ScanStream,
                    request_deserializer=apme_dot_v1_dot_primary__pb2.ScanChunk.FromString,
                    response_serializer=apme_dot_v1_dot_primary__pb2.ScanResponse.SerializeToString,
            ),
            'Format': grpc.unary_unary_rpc_method_handler(
                    servicer.Format,
                    request_deserializer=apme_dot_v1_dot_primary__pb2.FormatRequest.FromString,
                    response_serializer=apme_dot_v1_dot_primary__pb2.FormatResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=apme_dot_v1_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=apme_dot_v1_dot_common__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'apme.v1.Primary', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('apme.v1.Primary', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Primary(object):
    """Primary is the orchestrator daemon: receives chunked fs, runs engine + validators, returns violations.
    """

    @staticmethod
    def Scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apme.v1.Primary/Scan',
            apme_dot_v1_dot_primary__pb2.ScanRequest.SerializeToString,
            apme_dot_v1_dot_primary__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/apme.v1.Primary/ScanStream',
            apme_dot_v1_dot_primary__pb2.ScanChunk.SerializeToString,
            apme_dot_v1_dot_primary__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Format(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apme.v1.Primary/Format',
            apme_dot_v1_dot_primary__pb2.FormatRequest.SerializeToString,
            apme_dot_v1_dot_primary__pb2.FormatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apme.v1.Primary/Health',
            apme_dot_v1_dot_common__pb2.HealthRequest.SerializeToString,
            apme_dot_v1_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
